version: "3.3"

services:
  node:
    build: .
    container_name: "lucky-adda-api"
    env_file:
    - ./.env
    environment:
      PORT: ${PORT}
    volumes:
    - logs:/application/public/logs
    ports: 
    - "${PORT}:${PORT}"
    # restart: on-failure
volumes:
  logs: